version: '3.9'

services:
  mariadb:
    image: my_mariadb
    container_name: _mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./wp_db:/var/lib/mysql
    networks:
      - network
    restart: on-failure
  nginx:
    image: my_nginx
    container_name: _nginx
    build: ./requirements/nginx
    ports: 
      - "443:443"
    volumes:
      - ./wp_files:/var/www/html
    restart: on-failure
    networks:
      - network
    depends_on:
      - wordpress
  wordpress:
    image: my_wordpress
    container_name: _wordpress
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - ./wp_files:/var/www/html
    restart: on-failure
    networks:
      - network
    depends_on:
      - mariadb

networks:
  network:

volumes:
  wp_db:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/achraf/data/mysql
  wp_files:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/achraf/data/wordpress


    