version: '3.7'

services:
  nginx:
    image: nginx
    container_name: inc_nginx
    build: ./requirements/nginx
    ports: 
      - "443:443"
    volumes:
      - ./wp_files:/var/www/html
    depends_on:
      - wordpress
    restart: on-failure
    networks:
      - network
  mariadb:
    image: mariadb
    container_name: inc_mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./wp_db:/var/lib/mysql
    #restart: on-failure
    networks:
      - network
  wordpress:
    image: wordpress
    container_name: inc_wordpress
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    restart: on-failure
    volumes:
      - ./wp_files:/var/www/html
    networks:
      - network

networks:
  network:

volumes:
  wp_db:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/achraf/data/mysql
  wp_files:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/achraf/data/wordpress


    