services:
  nginx:
    container_name: nginx
    build: ./requierements/nginx
    ports: "443:443"
    volumes:
    - wp_files:/var/www/html
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requierements/mariadb
    volumes:
      - wp_db:/var/lib/mysql
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requierements/wordpress
    depends_on:
      - mariadb
      - nginx
    restart: always