version: '3.7'

services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports: 
      - "443:443"
    volumes:
      - ./wp_files:/var/www/html
    restart: always
    networks:
      - network
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./wp_db:/var/lib/mysql
    restart: always
    networks:
      - network
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
      - nginx
    restart: always
    volumes:
      - ./wp_files:/var/www/html
    networks:
      - network

networks:
  network:
    driver: bridge
    