version: '3.7'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports: 
      - "443:443"
    volumes:
      - ./wp_files:/var/www/html
    restart: always
    networks:
      - network
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - ./wp_db:/var/lib/mysql
    restart: always
    networks:
      - network
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
      - nginx
    restart: always
    networks:
      - network