version: '3.9'

services:
  mariadb:
    image: mariadb:mine
    container_name: my_mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - network
    restart: on-failure
  nginx:
    image: nginx:mine
    container_name: my_nginx
    build: ./requirements/nginx
    ports: 
      - "443:443"
    volumes:
      - wp_files:/var/www/html
    restart: on-failure
    networks:
      - network
    depends_on:
      - wordpress
  wordpress:
    image: wordpress:mine
    container_name: my_wordpress
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - wp_files:/var/www/html
    restart: on-failure
    networks:
      - network
    depends_on:
      - mariadb
  redis:
    image: wp_redis:mine
    container_name: redis
    build: ./bonus/redis
    ports:
      - "6379:6379"
    depends_on:
      - wordpress
    restart: on-failure
  ftp:
    image: ftp:mine
    container_name: ftp
    build: ./bonus/ftp
    volumes:
      - wp_files:/var/www/html
    networks:
      - network
    ports:
      - "20:20"
      - "21:21"
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: on-failure
  staticWebsite:
    image: staticWebsite:mine
    container_name: staticWebsite
    build: ./bonus/static-web
    networks:
      - network
    ports:
      - "80:80"
    restart: on-failure

networks:
  network:

volumes:
  wp_db:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/achraf/data/mysql
  wp_files:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/achraf/data/wordpress


    