FROM debian:buster

RUN	apt-get update && apt upgrade -y \
	&& apt-get install curl php-fpm php-mysql -y

COPY ./config/setup.sh /tmp/setup.sh

RUN chmod +x /tmp/setup.sh

ENTRYPOINT ["/bin/sh" ,"/tmp/setup.sh"]